# generated by datamodel-codegen:
#   filename:  connection.schema.json
#   timestamp: 2025-04-02T09:19:19+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class Status(Enum):
    online = 'online'
    offline = 'offline'


class Connection(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    status: Status = Field(..., description='device status')
