# generated by datamodel-codegen:
#   filename:  error.schema.json
#   timestamp: 2025-04-02T09:19:19+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, conint

from .shared import position_schema


class Error(BaseModel):
    title: str = Field(..., description='short title for the error')
    code: str = Field(..., description='error code')
    description: Optional[str] = Field(
        None, description='long description of the error'
    )
    component: Optional[str] = Field(None, description='source component of error')
    severity: Optional[conint(ge=0, le=4)] = Field(None, description='severity')
    position: Optional[position_schema.DevicePosition] = Field(
        None, description='position at which the error occurred'
    )


class DeviceErrors(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    activeErrors: Optional[List[Error]] = None
