# generated by datamodel-codegen:
#   filename:  values.schema.json
#   timestamp: 2025-04-02T09:19:19+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, conint

from .shared import value_schema


class DeviceValues(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    interval: Optional[conint(ge=1)] = Field(
        None,
        description='Interval in seconds. The timestamp will be rounded to the nearest multiple of this interval.',
    )
    values: List[value_schema.ScalarValue]
