# generated by datamodel-codegen:
#   filename:  shared/position.schema.json
#   timestamp: 2025-04-02T09:19:19+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DevicePosition(BaseModel):
    z: float = Field(..., description='z position')
    x: float = Field(..., description='x position')
    y: float = Field(..., description='y position')
